Vagrant.configure("2") do |config|
  config.vm.box = "shakirshakiel/centos_guest_additions"
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y epel-release
    sudo yum install -y centos-release-openstack-queens
    sudo yum install -y diskimage-builder e4fsprogs dosfstools xfsprogs lvm2 policycoreutils-python gdisk
  SHELL
end
