Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y epel-release 
    sudo yum install -y nginx
    sudo systemctl start nginx
  SHELL
end
