Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/home/vagrant/files", type: "nfs"

  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network "private_network", ip: "10.10.10.10"
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y epel-release 
    sudo yum install -y nginx
    sudo systemctl start nginx
  SHELL
end
