Vagrant.configure("2") do |config|

  config.vm.box = "shakirshakiel/centos_guest_additions"
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y gcc-c++ net-tools unzip
  SHELL
  
end
  