Vagrant.configure("2") do |config|

    config.vm.box = "shakirshakiel/centos_docker"
    config.vm.box_version = "19.03.1"
    config.vm.provision "shell", inline: <<-SHELL
      yum install -y epel-release
      yum install -y git net-tools java-1.8.0-openjdk
      curl https://download.gocd.org/gocd.repo -o /etc/yum.repos.d/gocd.repo
      mkdir /var/go 
      yum install -y go-server go-agent
      chown -R go:go /var/run/go-agent /var/go
    SHELL
    
  end
    