Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y wget dkms binutils gcc make patch libgomp glibc-headers glibc-devel kernel-headers kernel-devel
    wget http://download.virtualbox.org/virtualbox/6.0.2/VBoxGuestAdditions_6.0.2.iso
    sudo mount VBoxGuestAdditions_6.0.2.iso -o loop /mnt
    sudo sh /mnt/VBoxLinuxAdditions.run --nox11
    sudo /opt/VBoxGuestAdditions-6.0.2/init/vboxadd setup
    sudo umount /mnt
    rm -rf VBoxGuestAdditions_6.0.2.iso
  SHELL
end
